# the name of your track or event
name = "Decentralized Science (DeSci)"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "Wes Floyd, Niklas Rindtorff, Eleanor D."

# the start date of the event
date = "2022-10-28"

# how many days the event lasts (1 - N)
days = 1

venueName = "Saffar"

# the event times (shows up in the event card)
times = "13:00 - 17:00"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the track.
# will show up when the user clicks the event card.
description = """
  DeSci aims to accelerate scientific breakthroughs and foster open collaboration via 
  Web3 technologies (IPFS) and crypto-incentives (IP-NFTs). In this track we will cover the 
  projects that are revolutionizing research through open collaboration on IPFS.
"""

# schedule is an array of timeslots objects
# schema:
#  startTime   - string for starting time
#  speakers    - array of string speaker names. please to use consistent naming across timeslots
#  title       - string for talk or timeslot title, should be short
#  description - string describing the timeslot. 1-3 sentences.
# 
# Notes:
# - recommended start: 09:00
# - recommended lunch: 12:00 or 13:00
# - recommended end:   17:00
# - use 15m, 20m, 30m, 45m, or 60m session slots
# - use 15m breaks, one in the morning, one or two in the afternoon
[[timeslots]]
startTime="13:00"
speakers=["Niklas Rindtorff"]
title="LabDAO (DeSci, LabDAO Overview, Partnership, etc.)"
description=""

[[timeslots]]
startTime="13:30"
speakers=["Wes Floyd"]
title="Bacalhau (Overview and DeSci Use Cases)"
description=""

[[timeslots]]
startTime="13:50"
speakers=["Carla Ostmann"]
title="Transforming big scientific data into interoperable research objects stored Open State"
description=""

[[timeslots]]
startTime="14:10"
speakers=[]
title="Break"
description=""

[[timeslots]]
startTime="14:20"
speakers=["Kelsie Nabben"]
title="DAO Science: organizational design as an emerging interdisciplinary science"
description=""


[[timeslots]]
startTime="14:40"
speakers=["Gordon Gould"]
title="DeSci Meets ReFi: Quantifying Marine Biodiversity with Open Meta-omics to Power Sustainable and Scalable Ocean Regeneration"
description=""


[[timeslots]]
startTime="15:00"
speakers=["Alexandra McCarroll"]
title="The Future of Privacy-Preserving Compute & DeSci"
description=""

[[timeslots]]
startTime="15:20"
speakers=["Martin Karlsson"]
title="Visual graph tools for weaving together historical, in progress and future data to coordinate decentralized research"
description=""


[[timeslots]]
startTime="15:40"
speakers=[]
title="Break"
description=""

[[timeslots]]
startTime="15:50"
speakers=["Silvia Bessa"]
title="Research Roadmapping - Mapping the Unknowns"
description=""


[[timeslots]]
startTime="16:00"
speakers=["LabDAO + Bacalhau"]
title="DeSci Pinning and Compute Workshop (IPFS and Bacalhau)"
description=""
