# the name of your track or event
name = "IPFS Community Roundtable"

# the start date of the event
date = "2022-10-30"

# how many days the event lasts (1 - N)
days = 1

venueName = "Hypatia"

# the event times (shows up in the event card)
times = "14:00 - 17:00"

# the name handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "Reid Wilkes"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Roundtable"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the event.
# will show up when the user clicks the event card.
description = """
An opportunity for IPFS implementers, contributors, and others in our community to get together and discuss roadmap,
challenges, and opportunities.

[See the forum for more information](https://discuss.ipfs.tech/t/announcing-ipfs-community-roundtable/15380)
"""
